### ISSUE TITLE
[Question] Why is the PagerfantaInterface deprecated?

### ISSUE THREAD

**Issue by mmenozzi** [BabDev/Pagerfanta#14]
Why is the PagerfantaInterface deprecated? And why is the suggested replacement a concrete implementation (the `Pagerfanta` class)?

**Comment by mbabker** [comment]
IIRC, I dug through the history once and the interface has been empty and deprecated ever since the original 1.0 release.  I've stayed on that path for now since I don't think there is any value in an empty interface here.

That said, the deprecation can still be re-evaluated and instead of removing it in 3.0 the interface could actually be filled in properly.

**Comment by ruudk** [comment]
How do I get rid of this deprecation warning? Every time a `Pagerfanta` is loaded, it will also load the `PagerfantaInterface` that triggers the deprecation. So there is no way to "fix" the deprecation until it's removed in a new release?

**Comment by mbabker** [comment]
After thinking it through, the interface is no longer deprecated as of the 2.4 release, and in 3.0 the interface will now actually require methods to be implemented instead of being an empty interface.
