### ISSUE TITLE
Fix Doctrine MongoDB ODM Adapter Test

### ISSUE THREAD

**Issue by mbabker** [BabDev/Pagerfanta#3]
The Doctrine MongoDB ODM adapter tests are mostly skipped right now because the test was originally written for 1.x of that package and not updated to support 2.x which made the `Doctrine\ODM\MongoDB\Query\Query` class final (and therefore cannot be mocked).

The tests for this adapter should be updated to validate the adapter's behavior.

(Note, `ext/mongodb` and the `doctrine/mongodb-odm` package are installed in the GitHub Actions builds, so the test environment should be usable enough)

**Comment by davidribeiro** [comment]
Hi @mbabker 
Is this issue still open? I can take a look at it if you want to

**Comment by mbabker** [comment]
Yes, it's still open.

**Comment by davidribeiro** [comment]
I can take a look at this if you want. Just tell me what branch should I use, I see that 2.x is the default one but there are branches as well I think

**Comment by mbabker** [comment]
The 2.x branch is fine since it's the oldest supported, I'll handle upmerging to 3.x whenever a pull request is merged.

And thanks for taking a look, I just don't work with MongoDB and don't know the Doctrine package well enough to do anything meaningful here.

**Comment by davidribeiro** [comment]
Done in #19 
Unfortunately, there's not a lot we can do since the Doctrine ODM package has this issue:
* \Doctrine\ODM\MongoDB\Query\Builder::getQuery should return some type of QueryInterface (and this interface should implement the \IteratorAggregate Interface)
* This way the \Doctrine\ODM\MongoDB\Query\Query class could be final but any unit tests would still be able to work without any kind of "bypassFinals"
