### ISSUE TITLE
Pagerfanta::getAdapter being deprecated without any fallback

### ISSUE THREAD

**Issue by skylord123** [BabDev/Pagerfanta#35]
Why is this being deprecated? There is no real replacement for this and it breaks functionality in my app.

I'm using the [FOSElasticaBundle](https://github.com/FriendsOfSymfony/FOSElasticaBundle) which uses this library internally. When I create pagination the FOS bundle handles creating the `Pagerfanta` class and assigning the adapter. There is no way for me to get access to the adapter except for using the `Pagerfanta::getAdapter` method. 

When I query elasticsearch there is an extra field that I can only access via the adapter to get my hit count per index. Example:

```
        $indexHits = [];
        foreach($results->getAdapter()->getAggregations()['_index']['buckets'] as $bucket) {
            $indexHits[$bucket['key']] = $bucket['doc_count'];
        }
```

Why is this being removed when there is no alternative? Doing without my hit count per index just isn't an option for me (and I am sure others will find access to this object rather handy for other similar purposes).

**Comment by skylord123** [comment]
Here is where this is being utilized in the elastica bundle:
https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/src/Finder/TransformedFinder.php#L74-L82

As you can see there is no way to access the `$paginatorAdapter` and that is why I require the `Pagerfanta::getAdapter` moving forward.

**Comment by mbabker** [comment]
I'd have to dig into how that bundle works to understand things here.

In general though, to create a `Pagerfanta` instance, you generally need two things:

- The data source (a static array, a query builder, or whatever is accepted by an adapter's constructor)
- An adapter

Considering the usual construction pattern is `new Pagerfanta(new Adapter($data))`, both the adapter and the data source should be available in the scope of wherever a `Pagerfanta` object is created.  So, it should be very rare that one needs to fetch the underlying data from the root `Pagerfanta` instance, especially away from the construction site.

`PagerfantaInterface::getAdapter()` has very little portability to an outside consumer as that is typed to the adapter interface.  So, only its methods can be reliably used and anything further relies on being aware of concrete implementations of the adapter that away from the construction site might cause code stability concerns (even in the example you've posted, you have no guarantee `$results->getAdapter()` will 100% of the time be an adapter which exposes a `getAggregations()` method with the data you're expecting).  It only gets worse when you're trying to do any kind of `$adapter->getFoo()` because not every adapter exposes the underlying data source and those that do have inconsistent APIs for exposing it.

There are ways you can use PHP's structure to keep accessing the Pagerfanta internals (which could also make your code a bit more type-safe), so these deprecations aren't 100% limiting, but I can see how they'd be annoying.

```php
<?php

namespace App\Pagerfanta;

use FOS\ElasticaBundle\Paginator\FantaPaginatorAdapter;
use Pagerfanta\Pagerfanta;

final class FantaPagerfantaDecorator extends Pagerfanta
{
    public function __construct(private Pagerfanta $decorated) {}

    public function getAdapter(): AdapterInterface
    {
        if (!($this->decorated->adapter instanceof FantaPaginatorAdapter)) {
            throw new \RuntimeException('Unexpected adapter instance');
        }

        return $this->decorated->adapter;
    }

    public function __call(string $method, array $arguments): mixed
    {
        if (!method_exists($this->decorated, $method)) {
            throw new \BadMethodCallException("Method $method does not exist on the Pagerfanta class");
        }

        return $this->decorated->$method(...$arguments);
    }
}

$results = new FantaPagerfantaDecorator($results);
```

Obviously, nothing is 100% locked in stone and if it turns out that https://github.com/BabDev/Pagerfanta/commit/92c9e915718c4fa453384d3c400c2ff298e288be really does cause a lot of headaches, it can be re-evaluated.  But, right now my stance is that for the majority use case I'd consider this part of the API to be a bit flaky and not something I want to encourage and that for those who do have legitimate use cases for it, there are ways to make things work.

**Comment by baldurrensch** [comment]
One possible change (though a big change in the FOSElasticaBundle) would be instead of returning a `Pagerfanta`, would be to return the Adapter and the user would pass it into a Pagerfanta themselves. Not awesome either.
